### ISSUE TITLE
Refactor import statement in log classes

### ISSUE THREAD

**Issue by pleonex** [rticommunity/rticonnextdds-logparser#13]
From #8. The current *practice* is to use import the log functions with a redundant name like:
```python
import logparser.debug.debug as debug
...
    regex.append([debug.on_ignored_message,
```

We need to find a better name like "debugLogging" or "debugFunctions".

We can discuss too if we should move the logging functions (like from *debug.py*) into a class.

**Comment by iblancasa** [comment]
We should move the classes related to logs to a new folder (for example "logs"). Also, move logs.py. It will encapsulate the logs and will improve the file structure

**Comment by iblancasa** [comment]
Can we close this issue?
