### ISSUE TITLE
The ignored messages are print in unmatched.txt

### ISSUE THREAD

**Issue by iblancasa** [rticommunity/rticonnextdds-logparser#4]
When you activate the --debug parameter, the messages handled by on_ignored_message are printed in the unmatched.txt file. It is confusing because you can not differentiate the messages that are parsed from the messages that are ignored.

**Comment by pleonex** [comment]
The messages parsed with `on_ignored_message` should not be added to the _unmached.txt_ file.
- Did you check that the regex is being applied correctly?
- Which messages have the issue?
- Can you send a reproducer 😝 ?

**Comment by iblancasa** [comment]
- **Did you check that the regex is being applied correctly?**
  Yes. This happen with old regex and with the proposed in [PR1](https://github.com/rticommunity/rticonnextdds-logparser/pull/1)
- **Which messages have the issue?**
  All the messages that match with regex handled by on_ignored_message. I do not know if other methods from `debug.py` are affected.
- **Can you send a reproducer :stuck_out_tongue_closed_eyes: ?**

This is with one of the old regex.

```
Recv Resource:
      transport: 1 (UDPv4)
      address: 239.255.0.1
      port: 7400
      encapsulation:
   transport_priority: 0
   aliasList: ""

```

**Comment by iblancasa** [comment]
I found the problem. Is related to the regular expressions. I will open a PR in some time ;)

I will go ahead and close the issue
